# Generated by Django 4.2.4 on 2023-09-28 22:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_store_address_alter_store_delivery_fee_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="store",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
