# Generated by Django 4.2.4 on 2023-09-26 22:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_product_category_alter_store_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="slug",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
