# Generated by Django 4.2.4 on 2023-09-29 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_order_status_order_total_orderitem_order_products"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="UF",
            field=models.CharField(blank=True, default="ro", max_length=2, null=True),
        ),
        migrations.AddField(
            model_name="store",
            name="city",
            field=models.CharField(
                blank=True, default="Ariquemes", max_length=100, null=True
            ),
        ),
    ]
