# Generated by Django 4.2.4 on 2023-09-29 13:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_store_uf_store_city"),
    ]

    operations = [
        migrations.AlterField(
            model_name="store",
            name="UF",
            field=models.CharField(blank=True, default="RO", max_length=2, null=True),
        ),
    ]
